version: "3.9"

services:
  database:
    build: .
    container_name: database
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog
      BLOG_USER: blog
      BLOG_PASSWORD: p@ssw0ord

volumes:
  pgdata:
